# Generated by Django 5.0.4 on 2024-05-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.IntegerField(max_length=20)),
                ('employer_name', models.CharField(max_length=50)),
                ('street_name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('zipcode', models.IntegerField(max_length=25)),
                ('email', models.EmailField(max_length=30)),
                ('number_of_employer', models.IntegerField(max_length=20)),
                ('department', models.CharField(max_length=50)),
            ],
        ),
    ]
