# Generated by Django 5.0.4 on 2024-05-15 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0004_employer_profile_federal_employer_identification_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer_profile',
            name='location',
            field=models.CharField(default='Indore', max_length=50),
            preserve_default=False,
        ),
    ]
